app/models.py
from app import db
from datetime import datetime
import re


def slugify(s):
	pattern = r'[^\w+]'
	return re.sub(pattern, '-', s)


class Post(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(140))
	slug = db.Column(db.String(140), unique=True)
	body = db.Column(db.Text)
	created = db.Column(db.DateTime, default=datetime.now())


	def __init__(self, *args, **kwargs):
		super(Post, self).__init__(*args, **kwargs)
		self.generate_slug()


	def generate_slug(self):
		if self.title:
			self.slug = slugify(self.title)

	def __repr__(self):
		return '<Post id: {}, title: {}>'.format(self.id, self.title)

app/app.py
from flask import Flask

from config import Configuration

from flask_sqlalchemy import SQLAlchemy


#переменная по умолчанию
#__name__ - это имя текущего файла (сейчас app.py)

app = Flask(__name__)
app.config.from_object(Configuration)


db = SQLAlchemy(app)

app/main.py
# from app.py импортируем переменную app
from app import app
import view
from app import db

# путь к файлу blueprint.py 
from posts.blueprint import posts


app.register_blueprint(posts, url_prefix='/blog')

# включение режима отладки напрямую:
# app.run(debug=True)

# но лучше использовать файл config.py и
# импортировать настройки 

# в app.py:
# from config import Configuration
# app.config.from_object(Configuration)

if __name__ == '__main__':
	app.run()

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post

posts = Blueprint('posts', __name__, template_folder='templates')

# потому что у нас есть url_prefix='/blog'
@posts.route('/')
def index2():
	posts = Post.query.all()
	return render_template('posts/index.html', posts=posts)

	#/app/posts/templates/posts
	# return render_template('posts/index.html')

@posts.route('/<slug>')
def post_detail(slug):
	post = Post.query.filter(Post.slug==slug).first()
	return render_template('posts/post_detail.html', post=post)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<title>
		{% block title%}

		{% endblock %} | Flask app
	</title>
</head>
<body>

	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{{ url_for('index') }}">Flask</a>
			</div> <!-- navbar-header -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">

					<li class="active"><a href="{{ url_for('posts.index2') }}">Blog <span class="sr-only">(current)</span></a></li>

					<li><a href="#">Link</a></li>
				</ul>

				<from class="navbar-form navbar-left">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search">
					</div> <!-- form-group -->
					<button type="submit" class="btn btn-default">Submit</button>
				</from>

				<ul class="nav navbar-nav navbar-right">
					<li><a href="#">Link</a></li>
				</ul>
			</div> <!-- collapse navbar-collapse -->
		</div> <!-- container-fluid -->
	</nav>

	<div class="container">
		<div class="row">
			<h1>
				{% block content_title %}

				{% endblock %}
			</h1>

			{% block content %}

			{% endblock %}
		</div>
	</div>

</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
	Index page
{% endblock %}


{% block content_title %}
	Index page
{% endblock %}

{% block content %}
	Some content
{% endblock %}